# Generated by Django 3.0.7 on 2022-12-13 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20221213_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecategory',
            name='level',
        ),
        migrations.RemoveField(
            model_name='articlecategory',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='articlecategory',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='articlecategory',
            name='tree_id',
        ),
        migrations.RemoveField(
            model_name='readerinterest',
            name='level',
        ),
        migrations.RemoveField(
            model_name='readerinterest',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='readerinterest',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='readerinterest',
            name='tree_id',
        ),
    ]
