# Generated by Django 3.0.7 on 2022-12-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_article_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='audio',
            field=models.FileField(upload_to='images/'),
        ),
    ]
