# Generated by Django 3.0.7 on 2022-12-13 01:54

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magazine', '0002_auto_20221213_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, upload_to='images/')),
                ('banner', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('keywords', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolArtImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.PartnerSchool')),
            ],
        ),
        migrations.RemoveField(
            model_name='articlecategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='images',
            name='article',
        ),
        migrations.RenameModel(
            old_name='Review',
            new_name='SchoolReview',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='ArticleCategory',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.AddField(
            model_name='partnerschool',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.SchoolArticle'),
        ),
        migrations.AlterField(
            model_name='schoolreview',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.SchoolArticle'),
        ),
    ]
