# Generated by Django 3.0.7 on 2022-12-17 00:44

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_auto_20221213_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerschool',
            name='article',
        ),
        migrations.RemoveField(
            model_name='schoolarticle',
            name='description',
        ),
        migrations.RemoveField(
            model_name='schoolarticle',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='schoolartimages',
            name='school',
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('keywords', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('coverimage', models.ImageField(upload_to='images/')),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField()),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.PartnerSchool')),
            ],
        ),
        migrations.AddField(
            model_name='schoolarticle',
            name='school',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='magazine.Magazine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolartimages',
            name='magazine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='magazine.Magazine'),
            preserve_default=False,
        ),
    ]
