# Generated by Django 3.0.7 on 2022-12-17 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0004_auto_20221217_0629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolartimages',
            old_name='title',
            new_name='artist',
        ),
    ]
