# Generated by Django 3.0.7 on 2022-12-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0005_auto_20221217_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='editor',
            field=models.CharField(default='student', max_length=255),
        ),
    ]
