# Generated by Django 3.0.7 on 2022-12-17 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0007_auto_20221217_0753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolarticle',
            old_name='school',
            new_name='magazine',
        ),
    ]
