# Generated by Django 3.0.7 on 2022-12-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0008_auto_20221217_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolarticle',
            name='writer',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
